### ISSUE TITLE
Add Manta Testnet and Subsequent Mainnet

### ISSUE THREAD

**Issue by shuhuiluo** [pcaversaccio/create2deployer#137]
Could you deploy the factory to [Manta testnet](https://pacific-info.manta.network/) and the subsequent mainnet when it's launched? The [deployer address](https://pacific-explorer.manta.network/address/0x554282Cf65b42fc8fddc6041eb24ce5E8A0632Ad) has been funded on testnet.
Thank you very much.

**Comment by pcaversaccio** [comment]
Added the testnet deployment via https://github.com/pcaversaccio/create2deployer/commit/3764a1dd6c8b7d3e7236978abe9574605257587f. Closing the issue until the mainnet is live. Please ping me in this issue once it's live and the deployer account is funded. Will do the deployment afterwards accordingly.

**Comment by pcaversaccio** [comment]
Made a new release of `xdeployer` (in case you use it for deployment): https://github.com/pcaversaccio/xdeployer/releases/tag/v2.1.4.
