### ISSUE TITLE
💥 Add Shardeum Betanet Deployment

### ISSUE THREAD

**Issue by kevupton** [pcaversaccio/create2deployer#144]
https://shardeum.org/betanet/

**Comment by pcaversaccio** [comment]
Are the `CREATE` and `CREATE2` opcodes on this chain EVM-equivalent? Please fund the deployer address: 0x554282Cf65b42fc8fddc6041eb24ce5E8A0632Ad, if you want me to deploy it on this testnet.

**Comment by pcaversaccio** [comment]
Implemented via https://github.com/pcaversaccio/create2deployer/commit/4491687bd0519c86c4846596e7ab96978f14cbd9. The block explorer doesn't allow for any contract verification, unfortunately. Anyways, it's deployed.
