### ISSUE TITLE
Adding support Arthera Network

### ISSUE THREAD

**Issue by dzaptech** [pcaversaccio/create2deployer#198]
Hi @pcaversaccio can you please deploy Create2 on https://chainlist.org/chain/10242 chain.
Team has transferred 5m unit gas pass to your address. https://explorer.arthera.net/tx/0x102f0e3e0c3d54f4dcbb9921de5e5738bb2b96f70be1eac36f754b3fff3b6b85

**Comment by pcaversaccio** [comment]
Closed via https://github.com/pcaversaccio/create2deployer/commit/8c56e2247f411638dddf9ad1167c05808434a28e.
