### ISSUE TITLE
Add Metis Andromeda Test and Main Network Deployments

### ISSUE THREAD

**Issue by vmmunoza** [pcaversaccio/create2deployer#200]
Please add Metis:

Mainnet: Androme
RPC: https://andromeda.metis.io/?owner=1088
ChainList: https://chainlist.org/chain/1088 

Testnet: Sepolia
RPC: https://sepolia.metisdevops.link
ChainList: https://chainlist.org/chain/59902

All info about the network can be found here:
https://docs.metis.io/dev/readme/quick-start

PS: Metis funds were sent to 0x554282Cf65b42fc8fddc6041eb24ce5E8A0632Ad

**Comment by pcaversaccio** [comment]
Deployed via https://github.com/pcaversaccio/create2deployer/commit/48293aba8ed3f57ddc737bd450cde87ddd1aa306.
