### ISSUE TITLE
💥 Add Taiko Hekla Test and Main Network Deployments

### ISSUE THREAD

**Issue by swarna1101** [pcaversaccio/create2deployer#205]
Please add Taiko:

Mainnet: 
RPC: https://rpc.taiko.xyz
ChainList: https://chainlist.org/chain/167000

Testnet: Hekla
RPC: https://rpc.hekla.taiko.xyz
ChainList: https://chainlist.org/chain/167009

**Comment by pcaversaccio** [comment]
How about also adding support for Taiko in my latest factory contract: https://github.com/pcaversaccio/createx? Can you fund both deployer accounts on Testnet and Prod:
- `0x554282Cf65b42fc8fddc6041eb24ce5E8A0632Ad` (create2deployer)
- `0xeD456e05CaAb11d66C4c797dD6c1D6f9A7F352b5` (CreateX)

I need around 0.3 ETH for both deployments.

**Comment by pcaversaccio** [comment]
I need 0.3 ETH on Taiko Testnet and Taiko Prod for each deployer address. Thus 2 x 0.3 in Taiko testnet and 2 x 0.3 on Taiko.

**Comment by swarna1101** [comment]
I have sent you on testnet, can you start on testnet deployment pls

**Comment by pcaversaccio** [comment]
The main network deployments are done as well: 
- `Create2Deployer`: https://taikoscan.io/address/0x13b0D85CcB8bf860b6b79AF3029fCA081AE9beF2
- `CreateX`: https://taikoscan.io/address/0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed
