### ISSUE TITLE
💥 Add Support for Mode and ZetaChain

### ISSUE THREAD

**Issue by ShivamDev31** [pcaversaccio/create2deployer#206]
Hi,

Can you please add support for 
Mode: https://chainlist.org/chain/34443
ZetaChain: https://chainlist.org/chain/7000
I have already transferred funds for deployment to 0x554282Cf65b42fc8fddc6041eb24ce5E8A0632Ad

**Comment by pcaversaccio** [comment]
Hey, thx for the deployment funds. It might take a week or so until I deploy it as I am currently travelling.

**Comment by pcaversaccio** [comment]
@ShivamDev31 can you please send me also enough native ETH on Mode & ZetaChain testnet so I can deploy it there as well. Thx.

**Comment by pcaversaccio** [comment]
Deployed via https://github.com/pcaversaccio/create2deployer/commit/be7237a872625e99d71876c19df7d0f691a68208. Thx for funding the deployer!
