### ISSUE TITLE
💥 Add 5ireChain Test and Main Network Deployments

### ISSUE THREAD

**Issue by dung5ire** [pcaversaccio/create2deployer#208]
5ireChain Mainnet : https://chainlist.org/chain/995

I have transferred funds to `0x554282Cf65b42fc8fddc6041eb24ce5E8A0632Ad` (https://5irescan.io/tx/0x7d9dcc32f9d3535ac63451eebc56a6c4f9ce83074ea67d134dd2ab27be16c130)

**Comment by pcaversaccio** [comment]
Resolved via https://github.com/pcaversaccio/create2deployer/commit/878c2b66209481888e393eab323a3efac0b996b5.
